services:
  escalafon:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: escalafon
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - /opt/escalafon/data:/app/src/files
    networks:
      - web

  postgres:
    image: postgres:latest
    container_name: postgres_escalafon
    restart: always
    environment:
      POSTGRES_USER: escalafon_user
      POSTGRES_PASSWORD: 9tLsJ1IVneQob02cSlkIA69
      POSTGRES_DB: escalafon
    ports:
      - "5433:5432"
    volumes:
      - /opt/postgresql_escalafon:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    driver: bridge
