/* eslint-disable @typescript-eslint/no-require-imports */
import type { Config } from "tailwindcss";

export default {
  darkMode: ["class", "class"],
  content: ["./src/pages/**/*.{js,ts,jsx,tsx,mdx}", "./src/components/**/*.{js,ts,jsx,tsx,mdx}", "./src/app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "bg-primary": "var(--bg-primary)",
        "bg-main": "var(--bg-main)",
        "bg-section": "var(--bg-section)",
        "bg-block": "var(--bg-block)",
        "bg-alt": "var(--bg-alt)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-card": "var(--bg-card)",
        "bg-elevated": "var(--bg-elevated)",
        "bg-button": "var(--bg-button)",
        "bg-dropdown": "var(--bg-dropdown)",
        "text-primary": "var(--text-primary)",
        "text-main": "var(--text-main)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-title": "var(--text-title)",
        "text-headline": "var(--text-headline)",
        "text-subtitle": "var(--text-subtitle)",
        "text-section": "var(--text-section)",
        "text-section-title": "var(--text-section-title)",
        "text-link": "var(--text-link)",
        "text-link-hover": "var(--text-link-hover)",
        "text-button": "var(--text-button)",
        "text-warning": "var(--text-warning)",
        "text-error": "var(--text-error)",
        "header-primary": "var(--header-primary)",
        "title-main": "var(--title-main)",
        "header-secondary": "var(--header-secondary)",
        "title-sub": "var(--title-sub)",
        "section-header": "var(--section-header)",
        "subsection-header": "var(--subsection-header)",
        "button-primary": "var(--button-primary)",
        "button-secondary": "var(--button-secondary)",
        "button-confirm": "var(--button-confirm)",
        "button-cancel": "var(--button-cancel)",
        "button-danger": "var(--button-danger)",
        "button-hover": "var(--button-hover)",
        "button-disabled": "var(--button-disabled)",
        "link-main": "var(--link-main)",
        "link-hover": "var(--link-hover)",
        "link-active": "var(--link-active)",
        "link-disabled": "var(--link-disabled)",
        "box-shadow": "var(--box-shadow)",
        "border-primary": "var(--border-primary)",
        "border-focus": "var(--border-focus)",
        "border-disabled": "var(--border-disabled)",
        "text-shadow": "var(--text-shadow)",
        "alert-success": "var(--alert-success)",
        "alert-warning": "var(--alert-warning)",
        "alert-error": "var(--alert-error)",
        "alert-info": "var(--alert-info)",
        "icon-main": "var(--icon-main)",
        "icon-hover": "var(--icon-hover)",
        "icon-action": "var(--icon-action)",
        "icon-disabled": "var(--icon-disabled)",
        "navbar-background": "var(--navbar-background)",
        "footer-background": "var(--footer-background)",
        "input-checked": "var(--input-checked)",
        "input-placeholder": "var(--input-placeholder)",
        "loading-bar": "var(--loading-bar)",
        "loading-spinner": "var(--loading-spinner)",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("tailwindcss-animate")],
} satisfies Config;
