export const ubigeos = [
  {
    id: 1,
    inei: "010101",
    reniec: "12345678",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "Miraflores",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    inei: "010102",
    reniec: "23456789",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "San Isidro",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    inei: "020101",
    reniec: "34567890",
    departamento: "Arequipa",
    provincia: "Arequipa",
    distrito: "Arequipa",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    inei: "030101",
    reniec: "45678901",
    departamento: "Cusco",
    provincia: "Cusco",
    distrito: "Cusco",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    inei: "040101",
    reniec: "56789012",
    departamento: "Piura",
    provincia: "Piura",
    distrito: "Piura",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const cargos = [
  {
    id: 1,
    nombre: "Director Regional de Salud",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    nombre: "Gerente de Planeamiento y Presupuesto",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    nombre: "Subgerente de Recursos Humanos",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    nombre: "Jefe de la Oficina de Asesoría Legal",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    nombre: "Coordinador de Gestión Ambiental",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const dependencias = [
  {
    id: 1,
    nombre: "Dirección Regional de Educación",
    direccion: "Av. Universitaria 123, Lima",
    codigo: "DRE-001",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    nombre: "Oficina de Planificación y Presupuesto",
    direccion: "Calle 9 de Diciembre 456, Arequipa",
    codigo: "OPP-002",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    nombre: "Secretaría Técnica de Contrataciones",
    direccion: "Jr. San Martín 789, Cusco",
    codigo: "STC-003",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    nombre: "Unidad de Gestión de Proyectos",
    direccion: "Calle del Sol 234, Piura",
    codigo: "UGP-004",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    nombre: "Oficina de Seguridad y Salud en el Trabajo",
    direccion: "Av. Libertad 567, Trujillo",
    codigo: "OSST-005",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const users = [
  { id: 1, nombres: "Carlos Alberto", apellidos: "Pérez González", email: "carlos.perez@email.com", status: "disabled", ubigeoId: 1 },
  { id: 2, nombres: "Laura Isabel", apellidos: "Ramírez Martínez", email: "laura.ramirez@email.com", status: "disabled", ubigeoId: 2 },
  { id: 3, nombres: "Juan Carlos", apellidos: "Gómez Sánchez", email: "juan.gomez@email.com", status: "disabled", ubigeoId: 3 },
  { id: 4, nombres: "Pedro Antonio", apellidos: "López Palomino", email: "pedro.lopez@email.com", status: "disabled", ubigeoId: 4 },
  { id: 5, nombres: "Ana María", apellidos: "Mendoza Torres", email: "ana.lopez@email.com", status: "disabled", ubigeoId: 4 },
];

export const personales = [
  {
    id: 1,
    apellidoPaterno: "Pérez",
    apellidoMaterno: "González",
    nombres: "Carlos Alberto",
    sexo: "M",
    edad: 32,
    dni: "12345678",
    nAutogenerado: "NA001",
    licenciaConducir: "B",
    grupoSanguineo: "O_POSITIVO",
    fechaIngreso: new Date("2015-04-20"),
    unidadEstructurada: "Oficina de Recursos Humanos",
    fechaNacimiento: new Date("1992-06-15"),
    nacionalidad: "Peruano",
    ubigeoId: 1,
    domicilio: "Av. Principal 123, Lima",
    telefono: "987654321",
    celular: "987654321",
    email: "carlos.perez@email.com",
    regimenPensionario: "L. N° 29903",
    nombreAfp: "AFP Integra",
    situacionLaboral: "Nombrado-D.L. 276",
    estadoCivil: "S",
    discapacidad: true,
    cargoId: 1,
    dependenciaOficinaId: 1,
    discapacidadId: 1,
    conyugeId: null,
    status: "disabled",
  },
  {
    id: 2,
    apellidoPaterno: "Ramírez",
    apellidoMaterno: "Martínez",
    nombres: "Laura Isabel",
    sexo: "F",
    edad: 28,
    dni: "23456789",
    nAutogenerado: "NA002",
    licenciaConducir: "A",
    grupoSanguineo: "B_POSITIVO",
    fechaIngreso: new Date("2019-09-10"),
    unidadEstructurada: "Oficina de Planeamiento",
    fechaNacimiento: new Date("1997-03-25"),
    nacionalidad: "Peruana",
    ubigeoId: 2,
    domicilio: "Jr. Sol 456, Arequipa",
    telefono: "988877666",
    celular: "988877666",
    email: "laura.ramirez@email.com",
    regimenPensionario: "D. L. ° 19990",
    nombreAfp: "AFP Habitat",
    situacionLaboral: "Contratada plaza vacante",
    estadoCivil: "S",
    discapacidad: false,
    cargoId: 2,
    dependenciaOficinaId: 2,
    discapacidadId: null,
    conyugeId: null,
    status: "disabled",
  },
  {
    id: 3,
    apellidoPaterno: "Gómez",
    apellidoMaterno: "Sánchez",
    nombres: "Juan Carlos",
    sexo: "M",
    edad: 35,
    dni: "34567890",
    nAutogenerado: "NA003",
    licenciaConducir: "B",
    grupoSanguineo: "A_NEGATIVO",
    fechaIngreso: new Date("2017-01-12"),
    unidadEstructurada: "Oficina de Logística",
    fechaNacimiento: new Date("1989-10-05"),
    nacionalidad: "Peruano",
    ubigeoId: 3,
    domicilio: "Calle Futura 789, Trujillo",
    telefono: "944332211",
    celular: "944332211",
    email: "juan.gomez@email.com",
    regimenPensionario: "L. N° 29903",
    nombreAfp: "AFP Prima",
    situacionLaboral: "Contratado ley 30057",
    estadoCivil: "C",
    discapacidad: false,
    cargoId: 3,
    dependenciaOficinaId: 3,
    discapacidadId: null,
    conyugeId: null,
    status: "disabled",
  },
  {
    id: 4,
    apellidoPaterno: "López",
    apellidoMaterno: "Palomino",
    nombres: "Pedro Antonio",
    sexo: "M",
    edad: 40,
    dni: "45678901",
    nAutogenerado: "NA004",
    licenciaConducir: "A1",
    grupoSanguineo: "O_NEGATIVO",
    fechaIngreso: new Date("2010-08-15"),
    unidadEstructurada: "Oficina de Tecnología",
    fechaNacimiento: new Date("1984-07-12"),
    nacionalidad: "Peruano",
    ubigeoId: 4,
    domicilio: "Av. San Martín 1010, Piura",
    telefono: "967654321",
    celular: "967654321",
    email: "pedro.lopez@email.com",
    regimenPensionario: "D. L. ° 19990",
    nombreAfp: "AFP Integra",
    situacionLaboral: "Nombrado-D.L. 276",
    estadoCivil: "D",
    discapacidad: false,
    cargoId: 4,
    dependenciaOficinaId: 4,
    discapacidadId: null,
    conyugeId: 5,
    status: "disabled",
  },
  {
    id: 5,
    apellidoPaterno: "Mendoza",
    apellidoMaterno: "Torres",
    nombres: "Ana María",
    sexo: "F",
    edad: 38,
    dni: "56789012",
    nAutogenerado: "NA005",
    licenciaConducir: "B",
    grupoSanguineo: "A_POSITIVO",
    fechaIngreso: new Date("2012-05-10"),
    unidadEstructurada: "Oficina de Recursos Humanos",
    fechaNacimiento: new Date("1986-09-25"),
    nacionalidad: "Peruana",
    ubigeoId: 4,
    domicilio: "Av. San Martín 1010, Piura",
    telefono: "967654322",
    celular: "967654322",
    email: "ana.lopez@email.com",
    regimenPensionario: "L. N° 29903",
    nombreAfp: "AFP Prima",
    situacionLaboral: "Nombrada-D.L. 276",
    estadoCivil: "V",
    discapacidad: false,
    cargoId: 5,
    dependenciaOficinaId: 5,
    discapacidadId: null,
    conyugeId: 4,
    status: "disabled",
  },
];

export const conyuges = [
  {
    id: 1,
    userId: 3,
    personalId: 4,
    fechaNacimiento: new Date("1986-09-25"),
    gradoInstruccion: "Universitaria",
    profesion: "Abogada",
    ocupacion: "Consultora",
    centroTrabajo: "Ministerio de Justicia",
    postgrado: "Sí",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    userId: 4,
    personalId: 5,
    fechaNacimiento: new Date("1984-07-12"),
    gradoInstruccion: "Universitario",
    profesion: "Ingeniero de Sistemas",
    ocupacion: "Gerente de IT",
    centroTrabajo: "Ministerio de Tecnología",
    postgrado: "No",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const hijos = [
  {
    id: 1,
    userId: 5,
    personalId: 3,
    nombres: "Luis Alejandro",
    fechaNacimiento: new Date("2020-02-28"),
    edad: 4,
    ubigeoId: 3,
    gradoInstruccion: "Preescolar",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    userId: 6,
    personalId: 5,
    nombres: "Carlos Andrés",
    fechaNacimiento: new Date("2015-11-20"),
    edad: 9,
    ubigeoId: 4,
    gradoInstruccion: "Primaria",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const discapacidades = [
  {
    id: 1,
    personalId: 1,
    tipo: "Parálisis cerebral",
    documentoSustento: "Certificado Médico",
    organoEstructurado: "Departamento de Salud",
    condicionLaboral: "Ajustado a funciones especiales",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const estudios = [
  {
    id: 1,
    personalId: 1,
    nivel: "Universitario Titulado",
    periodo: "01/01/2010 - 01/12/2014",
    institucion: "Universidad Nacional de Ingeniería",
    otrosEstudios: "Certificación en Gestión de Proyectos",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    personalId: 2,
    nivel: "Secundaria Completa",
    periodo: "01/03/2008 - 01/12/2012",
    institucion: "Instituto Pedagógico San Martín",
    otrosEstudios: null,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    personalId: 3,
    nivel: "Técnico Titulado",
    periodo: "01/01/2006 - 01/12/2009",
    institucion: "Instituto Técnico de Electrónica",
    otrosEstudios: "Curso de Instalación de Redes Eléctricas",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    personalId: 4,
    nivel: "Postgrado",
    periodo: "01/01/2015 - 01/12/2017",
    institucion: "Universidad de Piura",
    otrosEstudios: "Diplomado en Innovación Tecnológica",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    personalId: 5,
    nivel: "Bachiller Universitario",
    periodo: "01/01/2008 - 01/12/2012",
    institucion: "Universidad Nacional de Trujillo",
    otrosEstudios: "Seminario de Desarrollo Personal",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const capacitaciones = [
  {
    id: 1,
    personalId: 1,
    centroCapacitacion: "Academia de Gestión de Proyectos",
    materia: "Gestión de Proyectos Ágiles",
    especialidad: "Gerente de Proyectos",
    periodo: "01/05/2020 - 01/10/2020",
    horasLectivas: 80,
    fechaEmision: new Date("2020-10-15"),
    certificadoPdf: "certificado_gestion_agile_2020.pdf",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    personalId: 2,
    centroCapacitacion: "Escuela de Capacitación Laboral",
    materia: "Técnicas de Resolución de Conflictos",
    especialidad: "Recursos Humanos",
    periodo: "01/03/2021 - 01/06/2021",
    horasLectivas: 40,
    fechaEmision: new Date("2021-06-10"),
    certificadoPdf: "certificado_resolucion_conflictos_2021.pdf",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    personalId: 3,
    centroCapacitacion: "Instituto de Redes Eléctricas",
    materia: "Instalación de Sistemas Eléctricos en Edificaciones",
    especialidad: "Técnico Electricista",
    periodo: "01/09/2018 - 01/12/2018",
    horasLectivas: 120,
    fechaEmision: new Date("2018-12-20"),
    certificadoPdf: "certificado_instalacion_redes_2018.pdf",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    personalId: 4,
    centroCapacitacion: "Centro de Innovación Tecnológica",
    materia: "Transformación Digital en Empresas",
    especialidad: "Tecnología y Gestión",
    periodo: "01/06/2020 - 01/11/2020",
    horasLectivas: 100,
    fechaEmision: new Date("2020-11-25"),
    certificadoPdf: "certificado_transformacion_digital_2020.pdf",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    personalId: 5,
    centroCapacitacion: "Universidad de Trujillo",
    materia: "Técnicas de Comunicación Eficaz",
    especialidad: "Comunicación Corporativa",
    periodo: "01/02/2022 - 01/05/2022",
    horasLectivas: 50,
    fechaEmision: new Date("2022-05-10"),
    certificadoPdf: "certificado_comunicacion_eficaz_2022.pdf",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const experienciaLaboral = [
  {
    id: 1,
    personalId: 1,
    documentoSustento: "Certificado de Trabajo",
    centroLabor: "Ministerio de Educación",
    dependenciaOficinaId: 1,
    cargoId: 1,
    periodo: "01/01/2018 - 31/12/2019",
    fechaEmision: new Date("2020-01-15"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    personalId: 1,
    documentoSustento: "Resolución Administrativa",
    centroLabor: "Gobierno Regional de Arequipa",
    dependenciaOficinaId: 2,
    cargoId: 2,
    periodo: "01/02/2020 - 30/06/2021",
    fechaEmision: new Date("2021-07-10"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    personalId: 2,
    documentoSustento: "Constancia de Trabajo",
    centroLabor: "Instituto Nacional de Estadística",
    dependenciaOficinaId: 3,
    cargoId: 3,
    periodo: "01/07/2021 - 31/12/2022",
    fechaEmision: new Date("2023-01-10"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    personalId: 2,
    documentoSustento: "Contrato CAS",
    centroLabor: "Municipalidad de Arequipa",
    dependenciaOficinaId: 4,
    cargoId: 4,
    periodo: "01/01/2023 - 31/12/2023",
    fechaEmision: new Date("2023-06-15"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    personalId: 2,
    documentoSustento: "Contrato de Locación de Servicios",
    centroLabor: "Universidad Nacional de Arequipa",
    dependenciaOficinaId: 5,
    cargoId: 5,
    periodo: "01/02/2024 - 01/08/2024",
    fechaEmision: new Date("2024-02-01"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    personalId: 3,
    documentoSustento: "Certificado de Trabajo",
    centroLabor: "Electroperú",
    dependenciaOficinaId: 1,
    cargoId: 1,
    periodo: "01/03/2015 - 31/12/2016",
    fechaEmision: new Date("2017-01-10"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    personalId: 3,
    documentoSustento: "Resolución Administrativa",
    centroLabor: "Ministerio de Energía y Minas",
    dependenciaOficinaId: 2,
    cargoId: 2,
    periodo: "01/02/2017 - 31/12/2018",
    fechaEmision: new Date("2019-01-20"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    personalId: 3,
    documentoSustento: "Constancia de Trabajo",
    centroLabor: "Red Eléctrica Nacional",
    dependenciaOficinaId: 3,
    cargoId: 3,
    periodo: "01/01/2019 - 31/12/2020",
    fechaEmision: new Date("2021-02-01"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    personalId: 4,
    documentoSustento: "Contrato CAS",
    centroLabor: "Distribuidora Eléctrica",
    dependenciaOficinaId: 4,
    cargoId: 4,
    periodo: "01/01/2021 - 31/12/2022",
    fechaEmision: new Date("2022-06-10"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    personalId: 5,
    documentoSustento: "Contrato de Locación de Servicios",
    centroLabor: "Instituto de Energía y Tecnología",
    dependenciaOficinaId: 5,
    cargoId: 5,
    periodo: "01/01/2023 - 31/12/2023",
    fechaEmision: new Date("2023-01-05"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const contratos = [
  {
    id: 1,
    tipoContrato: "DECRETO_LEGISLATIVO_276",
    condicionLaboral: "Nombrado conforme a la Ley N° 276",
    resolucionNombramiento: "Resolución N° 1234/2015",
    regimenLaboral: "Ley N° 276",
    nivelRemuneracion: "S/. 3,000",
    pap: "Documento PAP",
    cnp: "CNP-123456",
    fechaIngreso: new Date("2015-04-20"),
    fechaCese: null,
    aniosServicio: 9,
    personalId: 1,
    dependenciaOficinaId: 1,
    cargoId: 1,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    tipoContrato: "CAS",
    condicionLaboral: "Contrato Administrativo de Servicios",
    resolucionNombramiento: "Resolución N° 5678/2019",
    regimenLaboral: "Ley N° 30057",
    nivelRemuneracion: "S/. 2,500",
    pap: "Documento PAP",
    cnp: "CNP-987654",
    fechaIngreso: new Date("2019-09-10"),
    fechaCese: null,
    aniosServicio: 5,
    personalId: 2,
    dependenciaOficinaId: 2,
    cargoId: 2,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    tipoContrato: "PROYECTO_INVERSION",
    condicionLaboral: "Contratación por Proyecto de Inversión",
    resolucionNombramiento: "Resolución N° 8765/2017",
    regimenLaboral: "Proyecto de Inversión Ley N° 30057",
    nivelRemuneracion: "S/. 3,500",
    pap: "Documento PAP",
    cnp: "CNP-112233",
    fechaIngreso: new Date("2017-01-12"),
    fechaCese: null,
    aniosServicio: 8,
    personalId: 3,
    dependenciaOficinaId: 3,
    cargoId: 3,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    tipoContrato: "DECRETO_LEGISLATIVO_276",
    condicionLaboral: "Nombrado conforme a la Ley N° 276",
    resolucionNombramiento: "Resolución N° 8901/2010",
    regimenLaboral: "Ley N° 276",
    nivelRemuneracion: "S/. 4,000",
    pap: "Documento PAP",
    cnp: "CNP-223344",
    fechaIngreso: new Date("2010-08-15"),
    fechaCese: null,
    aniosServicio: 14,
    personalId: 4,
    dependenciaOficinaId: 4,
    cargoId: 4,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    tipoContrato: "CAS",
    condicionLaboral: "Contrato Administrativo de Servicios",
    resolucionNombramiento: "Resolución N° 4567/2012",
    regimenLaboral: "Ley N° 30057",
    nivelRemuneracion: "S/. 3,200",
    pap: "Documento PAP",
    cnp: "CNP-334455",
    fechaIngreso: new Date("2012-05-10"),
    fechaCese: null,
    aniosServicio: 12,
    personalId: 5,
    dependenciaOficinaId: 5,
    cargoId: 5,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const renunciaLiquidaciones = [
  {
    id: 1,
    documentoRenuncia: "Carta de Renuncia N° 123/2024",
    motivoRenuncia: "Motivo personal",
    fechaRenuncia: new Date("2024-01-15"),
    personalId: 2,
    dependenciaOficinaId: 2,
    cargoId: 2,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    documentoRenuncia: "Resolución de Renuncia N° 456/2024",
    motivoRenuncia: "Motivo de salud",
    fechaRenuncia: new Date("2024-02-01"),
    personalId: 5,
    dependenciaOficinaId: 5,
    cargoId: 5,
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const desplazamientos = [
  {
    id: 1,
    personaId: 4,
    fechaInicio: new Date("2025-02-10"),
    fechaFin: new Date("2025-02-15"),
    motivo: "Reunión de trabajo en Lima",
    dependenciaDestinoId: 1, // Dirección Regional de Educación
    direccionDestino: "Av. Universitaria 123, Lima",
    estado: "Pendiente", // o "Aprobado" según sea el caso
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const descansosMedicos = [
  {
    id: 1,
    tipoDescanso: "MEDICO",
    documentoSustento: "Certificado médico N° 12345",
    fechaInicioDescanso: new Date("2025-02-01"),
    fechaFinDescanso: new Date("2025-02-10"),
    dependenciaOficinaId: 4, // Unidad de Gestión de Proyectos
    cargoId: 4, // Jefe de la Oficina de Asesoría Legal
    personalId: 4, // Pedro Antonio López
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const permisosLicenciasVacaciones = [
  {
    id: 1,
    tipoPermisoLicenciaVacacion: "VACACIONES",
    documentoSustento: "Solicitud de Vacaciones",
    fechaInicioPermiso: new Date("2025-03-01"),
    fechaFinPermiso: new Date("2025-03-15"),
    dependenciaOficinaId: 4, // Unidad de Gestión de Proyectos
    cargoId: 4, // Jefe de la Oficina de Asesoría Legal
    personalId: 4, // Pedro Antonio López
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const ascensos = [
  {
    id: 1,
    resolucionAscenso: "Resolución N° 56789",
    cargoDel: "Asistente Legal",
    cargoAl: "Jefe de la Oficina de Asesoría Legal",
    nivelRemunerativoDel: "S/ 2,500",
    nivelRemunerativoAl: "S/ 4,000",
    papDel: "Analista",
    papAl: "Líder",
    cnp: "CNP-12345",
    dependenciaId: 4, // Unidad de Gestión de Proyectos
    oficinaId: 4, // Unidad de Gestión de Proyectos
    personalId: 4, // Pedro Antonio López
    cargoDelId: 3, // Subgerente de Recursos Humanos
    cargoAlId: 4, // Jefe de la Oficina de Asesoría Legal
    dependenciaOficinaId: 4, // Unidad de Gestión de Proyectos
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const bonificacionesPersonales = [
  {
    id: 1,
    tipoBonificacion: "Bonificación por Desempeño",
    resolucionBonificacion: "Resolución N° 78901",
    dependenciaOficinaId: 5, // Oficina de Seguridad y Salud en el Trabajo
    cargoId: 5, // Coordinador de Gestión Ambiental
    personalId: 5, // Ana María López
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const bonificacionesFamiliares = [
  {
    id: 1,
    tipoBonificacion: "Bonificación Familiar",
    resolucionBonificacion: "Resolución N° 89012",
    dependenciaOficinaId: 5, // Oficina de Seguridad y Salud en el Trabajo
    cargoId: 5, // Coordinador de Gestión Ambiental
    personalId: 5, // Ana María López
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const fichasEvaluacion = [
  {
    id: 1,
    documentoSustento: "Informe de Evaluación N° 23456",
    fechaEvaluacion: new Date("2024-11-15"),
    personalId: 5, // Ana María López
    dependenciaId: 5, // Oficina de Seguridad y Salud en el Trabajo
    cargoId: 5, // Coordinador de Gestión Ambiental
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const meritos = [
  {
    id: 1,
    personalId: 1, // Pedro Antonio López
    dependenciaOficinaId: 4, // Unidad de Gestión de Proyectos
    cargoId: 4, // Jefe de la Oficina de Asesoría Legal
    documentoSustento: "Resolución N° 12345 de Reconocimiento",
    fecha: new Date("2024-08-15"),
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const deméritos = [
  {
    id: 1,
    personalId: 1, // Pedro Antonio López
    dependenciaOficinaId: 4, // Unidad de Gestión de Proyectos
    cargoId: 4, // Jefe de la Oficina de Asesoría Legal
    documentoSustento: "Memorando N° 54321 de Amonestación",
    tipoSancion: "Amonestación",
    fechaSancion: "10/11/2024 - 10/11/2024",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const actasEntrega = [
  {
    id: 1,
    actaEentregadoPorId: 4, // Pedro Antonio López
    actaRecibidoPorId: 2, // Gerente de Planeamiento y Presupuesto
    dependenciaOficinaId: 4, // Unidad de Gestión de Proyectos
    cargoId: 2, // Gerente de Planeamiento y Presupuesto
    documentoSustento: "Acta de Entrega N° 67890",
    fecha: "10/02/2025 - 10/02/2025",
    status: "disabled",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
