export const mmltTypes = {
  personalFile: {
    personalInformation: {
      personalData: "IPersonalData",
      spouseData: "ISpouseData",
      childrenData: "IChildrenData",
    },
    studiesTraining: {
      studies: "IStudies",
      training: "ITraining",
    },
  },
};

/** ---------------------------------------------------------------------------------------------------------------------------------------------- */

export interface IFormData {
  type: "BasicInput" | "BasicSelect" | "InputDate" | "InputFile";
  fields: Array<IInputBasicFields | IBasicSelectFields | IInputDateFields | IInputFileLabels>;
}

export type InputsPersonalData = {
  names: string;
  paternalLastName: string;
  maternalLastName: string;
  firstName: string;
  gender: string;
  age: number;
  dni: string;
  autoGeneratedNumber: string;
  driverLicense: string;
  bloodGroup: string;
  bloodGroup: string;
  startDate: string;
  workUnit: string;
  position: string;
  birthDate: string;
  district: string;
  province: string;
  region: string;
  nationality: string;
  address: string;
  urbanization: string;
  landlinePhone: string;
  mobilePhone: string;
  email: string;
  regimenPensionario: string;
  personalConDiscapacidad: string;
  nombreAFP: string;
  situacionLaboral: string;
  estadoCivil: string;
};

export type InputsChildrenData = {
  fullName: string;
  birthPlaceAndDate: string;
  age: number;
  educationLevel: string;
};

export type InputsSpouseData = {
  fullName: string;
  birthPlaceAndDate: string;
  region: string;
  province: string;
  district: string;
  educationLevel: string;
  profession: string;
  occupation: string;
  workplace: string;
  postgraduate: string;
};

export type InputsStudiesData = {
  fullName: string;
  academicBackground: string;
  academicYear: string;
  institutionName: string;
  otherCertifications: string;
  trainingCenter: string;
  subject: string;
  professionOrSpecialty: string;
  trainingPeriod: string;
  lectiveHours: string;
  issueDate: string;
  certifiedPDF: string;
};
