export type InputsPersonalData = {
  names: string;
  paternalLastName: string;
  maternalLastName: string;
  firstName: string;
  gender: string;
  age: number;
  dni: string;
  autoGeneratedNumber: string;
  driverLicense: string;
  bloodGroup: string;
  bloodGroup: string;
  startDate: string; 
  workUnit: string;
  position: string;
  birthDate: string;
  district: string;
  province: string;
  region: string;
  nationality: string;
  address: string;
  urbanization: string;
  landlinePhone: string;
  mobilePhone: string;
  email: string;
  regimenPensionario: string;
  personalConDiscapacidad: string;
  nombreAFP: string;
  situacionLaboral: string;
  estadoCivil: string;
};

export type InputsChildrenData = {
  fullName: string;
  birthPlaceAndDate: string;  // Lugar y fecha de nacimiento
  age: number;
  educationLevel: string;  // Grado de instrucción
};

export type InputsSpouseData = {
  fullName: string;  // Apellidos y nombres
  birthPlaceAndDate: string;  // Lugar y fecha de nacimiento
  region: string;  // Departamento/Región
  province: string;  // Provincia
  district: string;  // Distrito
  educationLevel: string;  // Grado de instrucción
  profession: string;  // Profesión
  occupation: string;  // Ocupación
  workplace: string;  // Centro de trabajo
  postgraduate: string;  // Postgrado / Especialización (Título, Año, Universidad)
};

export type WorkSituation =
  | 'Nombrado-D-L. 276'
  | 'Contratado plaza vacante'
  | 'Contratado ley 30057'
  | 'Contratado CAS-Indeterminado'
  | 'Contratado en CAS-Temporal D.L. 1057'
  | 'Contratado en proyecto de inversión'
  | 'Practicantes preprofesionales-D.L. 1404'
  | 'Practicante profesional-D.L. 1004';

export  type CivilStatus =
  | 'Soltero/a'
  | 'Casado/a'
  | 'Separado/a'
  | 'Viudo/a'
  | 'Conviviente';

export type PensionRegime =
| 'L. N° 29903'
| 'D. L. ° 19990';

export type AcademicFormation =
| 'Primaria Completa'
| 'Primaria Incompleta'
| 'Incompleta'
| 'Universitario Secundaria Completa'
| 'Secundaria Completa'
| 'Universitario Incompleta'
| 'Bachiller'
| 'Titulado'
| 'Postgrado'
| 'Técnico Completo'
| 'Técnico Incompleta'
| 'Técnico Egresado'
| 'Técnico Titulado';

export type LaborCondition =
| 'Nombrado'
| 'Contratado o en plaza vacante'
| 'Designado';

export type LaborRegime =
| '276'
| 'FAG-CAS-FUN276';

export type EmploymentCondition =
| 'Indeterminado'
| 'Eventual';

export type EmploymentConditionSpecial =
| 'Contratado'
| 'Reincorporado-Mandato Judicial';