"use client";
import { InputTypea } from "@/components/forms/InputTypes";
import { SelectTypea } from "@/components/forms/SelectTypes";
import { InputsPersonalData } from "@/types";
import React from "react";
import { useForm, SubmitHandler } from "react-hook-form";

interface IFormData {
  label: string;
  name: keyof InputsPersonalData;
  size?: string;
  type: "input" | "select";
  options: InputTypeForm | SelectTypeForm;
}

interface InputTypeForm {
  placeholder: string;
}

interface SelectTypeForm {
  items: string[];
  defaultValue: string;
}

const FormTemplatea = () => {
  const { control, handleSubmit } = useForm<InputsPersonalData>();

  const formData: IFormData[] = [
    {
      label: "Apellido Paterno",
      name: "paternalLastName",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su apellido paterno",
      },
    },
    {
      label: "Apellido Materno",
      name: "maternalLastName",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su apellido materno",
      },
    },
    {
      label: "Nombres",
      name: "names",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese sus nombres",
      },
    },
    {
      label: "Sexo",
      name: "gender",
      type: "select",
      size: "medium",
      options: {
        items: ["Masculino", "Femenino", "Otro", "Prefiero no decirlo"],
        defaultValue: "Prefiero no decirlo",
      },
    },
    {
      label: "Edad",
      name: "age",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su edad",
      },
    },
    {
      label: "DNI (Carnet de extranjería)",
      name: "dni",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su DNI o Carnet de extranjería",
      },
    },
    {
      label: "N° de Autogenerado",
      name: "autoGeneratedNumber",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese el número autogenerado",
      },
    },
    {
      label: "Licencia de conducir",
      name: "driverLicense",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su licencia de conducir",
      },
    },
    {
      label: "Grupo sanguíneo",
      name: "bloodGroup",
      type: "select",
      size: "medium",
      options: {
        items: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
        defaultValue: "O+",
      },
    },
    {
      label: "Fecha de ingreso",
      name: "startDate",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese la fecha de ingreso",
      },
    },
    {
      label: "Unidad estructurada donde trabaja",
      name: "workUnit",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese la unidad estructurada donde trabaja",
      },
    },
    {
      label: "Cargo",
      name: "position",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su cargo",
      },
    },
    {
      label: "Fecha de Nacimiento",
      name: "birthDate",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su fecha de nacimiento",
      },
    },
    {
      label: "Distrito",
      name: "district",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su distrito",
      },
    },
    {
      label: "Provincia",
      name: "province",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su provincia",
      },
    },
    {
      label: "Departamento/Región",
      name: "region",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su departamento o región",
      },
    },
    {
      label: "Nacionalidad",
      name: "nationality",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su nacionalidad",
      },
    },
    {
      label: "Domicilio Av/Jr. Calle",
      name: "address",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su domicilio (Av/Jr. Calle)",
      },
    },
    {
      label: "Interior Urbanización",
      name: "urbanization",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su interior o urbanización",
      },
    },
    {
      label: "Teléfono fijo",
      name: "landlinePhone",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su teléfono fijo",
      },
    },
    {
      label: "Celular",
      name: "mobilePhone",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su número de celular",
      },
    },
    {
      label: "Correo electrónico",
      name: "email",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su correo electrónico",
      },
    },
    {
      label: "Personal con discapacidad",
      name: "personalConDiscapacidad",
      type: "select",
      size: "medium",
      options: {
        items: ["Sí", "No"],
        defaultValue: "No",
      },
    },
    {
      label: "Régimen pensionario",
      name: "regimenPensionario",
      type: "select",
      size: "medium",
      options: {
        items: ["L. N° 29903", "D. L. ° 19990"],
        defaultValue: "L. N° 29903",
      },
    },
    {
      label: "Nombre de AFP",
      name: "nombreAFP",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese el nombre de la AFP",
      },
    },
    {
      label: "Situación laboral",
      name: "situacionLaboral",
      type: "select",
      size: "large",
      options: {
        items: [
          "Nombrado-D-L. 276",
          "Contratado plaza vacante",
          "Contratado ley 30057",
          "Contratado CAS-Indeterminado",
          "Contratado en CAS-Temporal D.L. 1057",
          "Contratado en proyecto de inversión",
          "Practicantes preprofesionales-D.L. 1404",
          "Practicante profesional-D.L. 1004",
        ],
        defaultValue: "Nombrado-D-L. 276",
      },
    },
    {
      label: "Estado civil",
      name: "estadoCivil",
      type: "select",
      size: "medium",
      options: {
        items: [
          "Soltero/a",
          "Casado/a",
          "Separado/a",
          "Viudo/a",
          "Conviviente",
        ],
        defaultValue: "Soltero/a",
      },
    },
  ];

  const onSubmit: SubmitHandler<InputsPersonalData> = (data) =>
    console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {formData.map((field, index) =>
        field.type === "input" ? (
          <InputTypea
            key={index}
            label={field.label}
            name={field.name as keyof InputsPersonalData}
            type={field.type}
            control={control}
            options={field.options}
          />
        ) : (
          <SelectTypea
            key={index}
            label={field.label}
            name={field.name as keyof InputsPersonalData}
            control={control}
            options={field.options}
          />
        )
      )}
      <button type="submit">Enviar</button>
    </form>
  );
};

const page = () => {
  return (
    <div className="flex flex-col justify-center items-center font-poppins">
      <div className="flex flex-col">
        <h3 className="font-bold font-montserrat text-xl uppercase">
          Datos personales
        </h3>
        <FormTemplatea />
      </div>
    </div>
  );
};

export default page;
