"use client";
import { InputTypea } from "@/components/forms/InputTypes";
import { InputsPersonalData } from "@/types";
import React from "react";
import { useForm, SubmitHandler } from "react-hook-form";

interface IFormData {
  label: string;
  name: keyof InputsPersonalData;
  size?: string;
  type: "input" | "select";
  options: {
    placeholder: string;
  };
}

const FormTemplatea = () => {
  const { control, handleSubmit } = useForm<InputsPersonalData>();

  const formData: IFormData[] = [
    {
      label: "Apellido Paterno",
      name: "paternalLastName",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su apellido paterno",
      },
    },
    {
      label: "Apellido Materno",
      name: "maternalLastName",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su apellido materno",
      },
    },
    {
      label: "Nombres",
      name: "names",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese sus nombres",
      },
    },
    // {
    //   label: "Sexo",
    //   name: "gender",
    //   type: "select",
    //   size: "medium",
    //   options: {
    //     placeholder: "Seleccione su sexo",
    //   },
    // },
    {
      label: "Edad",
      name: "age",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su edad",
      },
    },
    {
      label: "DNI (Carnet de extranjería)",
      name: "dni",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su DNI o Carnet de extranjería",
      },
    },
    {
      label: "N° de Autogenerado",
      name: "autoGeneratedNumber",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese el número autogenerado",
      },
    },
    {
      label: "Licencia de conducir",
      name: "driverLicense",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su licencia de conducir",
      },
    },
    // {
    //   label: "Grupo sanguíneo",
    //   name: "bloodGroup",
    //   type: "select",
    //   size: "small",
    //   options: {
    //     placeholder: "Seleccione su grupo sanguíneo",
    //   },
    // },
    {
      label: "Fecha de ingreso",
      name: "startDate",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese la fecha de ingreso",
      },
    },
    {
      label: "Unidad estructurada donde trabaja",
      name: "workUnit",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese la unidad estructurada donde trabaja",
      },
    },
    {
      label: "Cargo",
      name: "position",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su cargo",
      },
    },
    {
      label: "Fecha de Nacimiento",
      name: "birthDate",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su fecha de nacimiento",
      },
    },
    {
      label: "Distrito",
      name: "district",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su distrito",
      },
    },
    {
      label: "Provincia",
      name: "province",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su provincia",
      },
    },
    {
      label: "Departamento/Región",
      name: "region",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su departamento o región",
      },
    },
    {
      label: "Nacionalidad",
      name: "nationality",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su nacionalidad",
      },
    },
    {
      label: "Domicilio Av/Jr. Calle",
      name: "address",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su domicilio (Av/Jr. Calle)",
      },
    },
    {
      label: "Interior Urbanización",
      name: "urbanization",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su interior o urbanización",
      },
    },
    {
      label: "Teléfono fijo",
      name: "landlinePhone",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su teléfono fijo",
      },
    },
    {
      label: "Celular",
      name: "mobilePhone",
      type: "input",
      size: "small",
      options: {
        placeholder: "Ingrese su número de celular",
      },
    },
    {
      label: "Correo electrónico",
      name: "email",
      type: "input",
      size: "medium",
      options: {
        placeholder: "Ingrese su correo electrónico",
      },
    },
  ];

  const onSubmit: SubmitHandler<InputsPersonalData> = (data) =>
    console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {formData.map((field, index) => (
        <InputTypea
          key={index}
          label={field.label}
          name={field.name as keyof InputsPersonalData}
          type={field.type}
          control={control}
          options={field.options}
        />
      ))}
      <button type="submit">Enviar</button>
    </form>
  );
};

const page = () => {
  return (
    <div className="flex flex-col justify-center items-center font-poppins">
      <div className="flex flex-col">
        <h3 className="font-bold font-montserrat text-xl uppercase">
          Información personal
        </h3>
        <FormTemplatea />
      </div>
    </div>
  );
};

export default page;
