import { IFormData } from "@/types";
import { LuCalendar, LuFile, LuGraduationCap, LuMap, LuUserRound } from "react-icons/lu";

/** /dashboard/personal-file/personal-information/personal-data */
export interface IPersonalData {
  paternalSurname: string; // Apellido Paterno
  maternalSurname: string; // Apellido Materno
  names: string; // Nombres
  gender: "m" | "f"; // Sexo
  age: number; // Edad
  dni: string; // DNI (Carnet de extranjería)
  autoGeneratedNumber: string; // N° de Autogenerado
  drivingLicense: string; // Licencia de conducir
  bloodGroup: string; // Grupo sanguíneo
  entryDate: string; // Fecha de ingreso
  workUnit: string; // Unidad estructurada donde trabaja
  position: string; // Cargo
  birthDate: string; // Fecha de Nacimiento
  district: string; // Distrito
  province: string; // Provincia
  department: string; // Departamento/Región
  nationality: string; // Nacionalidad
  address: string; // Domicilio Av/Jr. Calle
  interior: string; // Interior Urbanización
  phone: string; // Teléfono fijo
  mobile: string; // Celular
  email: string; // Correo electrónico
  disability: "si" | "no"; // Personal con discapacidad (si, no)
  pensionRegime: string; // Régimen pensionario (L. N° 29903, D. L. ° 19990)
  afpName: string; // Nombre de AFP
  employmentStatus: EmploymentStatus; // Situación laboral
  maritalStatus: MaritalStatus; // Estado civil
}

export enum EmploymentStatus {
  Appointed = "Nombrado-D-L. 276",
  HiredVacancyPosition = "Contratado plaza vacante",
  HiredLaw30057 = "Contratado ley 30057",
  HiredCASIndeterminate = "Contratado CAS-Indeterminado",
  HiredCASTemporary = "Contratado CAS-Temporal D.L. 1057",
  HiredInInvestmentProject = "Contratado en proyecto de inversión",
  PreProfessionalIntern = "Practicantes preprofesionales-D.L. 1404",
  ProfessionalIntern = "Practicante profesional-D.L. 1004",
}

export enum MaritalStatus {
  Single = "Soltero/a",
  Married = "Casado/a",
  Separated = "Separado/a",
  Widowed = "Viudo/a",
  LivingTogether = "Conviviente",
}

/** /dashboard/personal-file/personal-information/spouse-data */
export interface ISpouseData {
  names: string;
  lastName: string;
  placeBirth: string;
  birthdate: string;
  province: string;
  district: string;
  levelEducation: string;
  profession: string;
  occupation: string;
  workCenter: string;
  postgraduateSpecialization: string;
}

/** /dashboard/personal-file/personal-information/children-data */
export interface IChildrenData {
  names: string;
  lastName: string;
  placeBirth: string;
  birthdate: string;
  levelEducation: string;
}

export const childrenData: IFormData[] = [
  {
    type: "BasicInput",
    fields: [
      {
        label: "nombres",
        name: "names",
        placeholder: "ingrese sus nombres",
        icon: <LuUserRound />,
      },
      {
        label: "apellidos",
        name: "lastName",
        placeholder: "ingrese sus apellidos",
        icon: <LuUserRound />,
      },
    ],
  },
  {
    type: "BasicInput",
    fields: [
      {
        label: "lugar de naciemiento",
        name: "location",
        placeholder: "ingrese su lugar de nacimiento",
        icon: <LuMap />,
      },
      {
        label: "fecha de nacimiento",
        name: "birthdate",
        type: "date",
        icon: <LuCalendar />,
      },
      {
        label: "nivel de educación",
        name: "levelEducation",
        placeholder: "ingrese su nivel de educación",
        icon: <LuGraduationCap />,
      },
    ],
  },
];

/** /dashboard/personal-file/studies-training */
// only data for studies
export enum AcademicLevel {
  CompletedPrimary = "Primaria Completa",
  IncompletePrimary = "Primaria Incompleta",
  CompletedSecondary = "Secundaria Completa",
  IncompleteSecondary = "Secundaria Incompleta",
  CompletedUniversity = "Universitario Completo",
  IncompleteUniversity = "Universitario Incompleto",
  Bachelor = "Bachiller",
  DegreeHolder = "Titulado",
  Postgraduate = "Postgrado",
  CompletedTechnicalEducation = "Técnico Completo",
  IncompleteTechnicalEducation = "Técnico Incompleto",
  GraduatedTechnicalEducation = "Técnico Egresado",
  CertifiedTechnicalEducation = "Técnico Titulado",
}

export interface IStudies {
  fullName: string; // Apellidos y nombres
  academicFormation: AcademicLevel; // Formación Académica
  startYear: number; // Año (Del)
  endYear: number; // Año (Al)
  institutionName: string; // Nombre de la institución
  otherCertifiedStudies: string; // Otros estudios con certificación
}

// only data for training
export interface ITraining {
  names: string;
  lastName: string;
  trainingCenter: string;
  subject: string;
  professionOrSpecialty: string;
  periodStart: string;
  periodEnd: string;
  hours: number;
  issueDate: string;
  certificatePdf: string;
}

export interface IStudiesTraining {
  names: string;
  lastName: string;
  trainingCenter: string;
  subject: string;
  professionOrSpecialty: string;
  periodStart: string;
  periodEnd: string;
  hours: number;
  issueDate: string;
  certificatePdf: string;
}
export const studiesTraining: IFormData[] = [
  {
    type: "BasicInput",
    fields: [
      {
        label: "nombres",
        name: "names",
        placeholder: "Ingrese sus nombres",
        icon: <LuUserRound />,
      },
      {
        label: "apellidos",
        name: "lastName",
        placeholder: "ingrese sus apellidos",
        icon: <LuUserRound />,
      },
    ],
  },
  {
    type: "BasicInput",
    fields: [
      {
        label: "centro de formación",
        name: "trainingCenter",
        placeholder: "ingrese el centro de formación profesional",
        icon: <LuUserRound />,
      },
    ],
  },
  {
    type: "BasicInput",
    fields: [
      {
        label: "asignatura",
        name: "subject",
        placeholder: "ingrese la asignatura",
        icon: <LuUserRound />,
      },

      {
        label: "profesión o especialidad",
        name: "professionOrSpecialty",
        placeholder: "ingrese la profesión o especialidad",
        icon: <LuUserRound />,
      },
    ],
  },
  {
    type: "InputDate",
    fields: [
      {
        label: "periodo",
        name: "period",
      },
    ],
  },
  {
    type: "BasicInput",
    fields: [
      {
        label: "horas lectivas",
        name: "hours",
        placeholder: "ingrese las horas lectivas",
        icon: <LuUserRound />,
      },
    ],
  },
  {
    type: "BasicInput",
    fields: [
      {
        label: "fecha de emisión",
        name: "issueDate",
        placeholder: "ingrese la fecha de emisión",
        icon: <LuUserRound />,
      },
    ],
  },
  {
    type: "InputFile",
    fields: [
      {
        label: "certificado PDF",
        name: "certificatePdf",
        inf: "ingrese el certificado PDF",
        icon: <LuFile />,
      },
    ],
  },
];

/** /dashboard/personal-file/disability */
export interface IDisability {
  disabilityType: string; // Tipo de discapacidad (física, sensorial, intelectual, etc.)
  disabilityCertificate: string; // Certificado de discapacidad (Número de documento o código)
  disabilityDegree: string; // Grado de discapacidad (Leve, Moderada, Severa)
}

/**
 * FICHA PERSONAL
   ├── Datos Personales
   ├── Estudios y Capacitación
   ├── Experiencia Laboral
   └── Discapacidad
 */

/**
 * -- Datos personales (+ trabajador)
 * *** a. Datos personales
 * Apellido Paterno
 * Apellido Materno
 * Nombres
 * Sexo
 * Edad
 * DNI (Carnet de extranjería)
 * N° de Autogenerado
 * Licencia de conducir
 * Grupo sanguíneo
 * Fecha de ingreso
 * Unidad estructurada donde trabaja
 * Cargo
 * Fecha de Nacimiento
 * Distrito
 * Provincia
 * Departamento/Región
 * Nacionalidad
 * Domicilio Av/Jr. Calle
 * Interior Urbanización
 * Provincia
 * Distrito
 * Teléfono fijo
 * Celular
 * Correo electrónico
 * Personal con discapacidad (si, no)
 * Régimen pensionario (L. N° 29903, D. L. ° 19990)
 * Nombre de AFP
 * Situación laboral (Nombrado-D-L. 276, Contratado plaza vacante, Contratado ley 30057, Contratado CAS-Indeterminado, Contratado en CAS-Temporal D.L. 1057, Contratado en proyecto de inversión, Practicantes preprofesionales-D.L. 1404, Practicante profesional-D.L. 1004).
 * Estado civil (Soltero/a, Casado/a, Separado/a, Viudo/a, Conviviente)
 * *** b. Datos del Cónyuge
 * Apellidos y nombres
 * Lugar y fecha de nacimiento
 * Departamento/Región
 * Provincia
 * Distrito
 * Grado de instrucción
 * Profesión
 * Ocupación
 * Centro de Trabajo
 * Postgrado / Especialización (Título, Año, Universidad)
 * *** c. Datos de los hijos
 * Apellidos y nombres
 * Lugar y fecha de nacimiento
 * Edad
 * Grado de instrucción
 */

export type SpouseFormValues = {
  spouseFirstName: string;
  spouseLastName: string;
  spouseBirthPlace: string;
  spouseBirthDate: string;
  spouseAge: number;
  spouseEducationLevel: string;
  spouseProfession: string;
  spouseOccupation: string;
  spouseWorkplace: string;
  spousePostgraduateTitle: string;
  spousePostgraduateYear: string;
  spousePostgraduateUniversity: string;
};

export type ChildrenFormValues = {
  name: string;
  lastName: string;
  birthPlace: string;
  birthDate: string;
  age: number;
  educationLevel: string;
  email: string;
};

/**
 * -- Estudios y capacitación (+ trabajador)
 * *** a. Estudios
 * Apellidos y nombres
 * Formación Académica(Primaria Completa, Primaria Incompleta, Incompleta, Universitario Secundaria Completa, Secundaria Completa, Universitario Incompleta, Bachiller, Titulado, Postgrado, Técnico Completo, Técnico Incompleta, Técnico Egresado, Técnico Titulado)
 * Año(Del, Al)
 * Nombre de la institución
 * Otros estudios con certificación
 * *** b. Capacitación
 * Apellidos y nombres
 * Centro de capacitación
 * Materia
 * Profesión o especialidad
 * Periodo (Del, Al)
 * Horas Lectivas
 * Fecha de emisión
 * Certificado escaneado en PDF
 */

/**
 * -- Experiencia laboral (+ trabajador)
 * Apellidos y nombres
 * Documento de sustento (Certificado, Constancia, Resolución, CAS, Locación de servicio)
 * Centro de labor
 * Dependencia y/o oficina
 * Cargo
 * Periodo de labor (Del - Al)
 * Fecha de emisión
 */

/**
 * -- Personal con discapacidad (+ trabajador)
 * Apellidos y nombres
 * Sexo
 * DNI
 * Documento de sustento
 * Tipo de discapacidad
 * Cargo
 * Órgano estructurado
 * Condición laboral
 */
